name: CI - bachelor-meal

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22, 24] # Matrix for testing multiple Node versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checking out the repository to the CI environment

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # Set up the specified Node.js version
        with:
          node-version: ${{ matrix.node-version }} # Uses matrix variable for version

      - name: Install dependencies
        run: npm install # Installing project dependencies

      - name: Run tests with Vitest
        run: npm test # Running tests defined in package.json
